### ISSUE TITLE
Startup error on docker run

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/microservice#14]
To debug:
```ex
(node:56) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/opt/app/assets/node_modules/.cache/hard-source'
    at Object.mkdirSync (fs.js:921:3)
    at sync (/opt/app/assets/node_modules/mkdirp/index.js:72:13)
    at sync (/opt/app/assets/node_modules/mkdirp/index.js:78:24)
    at Function.sync (/opt/app/assets/node_modules/mkdirp/index.js:78:24)
    at runReadOrReset (/opt/app/assets/node_modules/hard-source-webpack-plugin/index.js:263:16)
    at _next0 (eval at create (/opt/app/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:17)
    at eval (eval at create (/opt/app/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:76:1)
(node:56) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by taylordowns2000** [comment]
Closed by ensuring that the docker app user owns their home dir
